version:
  "3"
services:
  urHandler:
    image: "ucsc-keysight/urhandler:latest"
    ports:
      - 6080:6080
      - 5900:5900
    restart: unless-stopped
    networks:
      ursim_net:
        ipv4_address: 192.168.56.101 
        
  openTapController:
    image: "ucsc-keysight/opentap:latest"
    #network_mode: host
    restart: unless-stopped
    mac_address: 00:1c:42:8a:53:9b
    depends_on:
      - urHandler
    networks:
      - ursim_net
    
    

networks:
  ursim_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.56.0/24
          gateway: 192.168.56.1
